layout_spectrum: 1
color:
  saturation: 0.3530466
  lightness: 0.5358423
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#8E8E8E'
    - '#CCCCCC'
    - '#585858'
  rhythmicContrast: 0.5376344
typography_spectrum: 0.05017921
name: The Moose The Band
